spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${BD_HOST}/voll.med
    username: ${BD_USER}
    password: ${BD_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  spring:
    flyway:
    locations: classpath:db/migration



hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

server:
  error:
    include-stacktrace: never


